name: Update README with GitHub Streak Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC daily

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "Updating README with the latest GitHub streak stats..."
          sed -i '/<p><img align="center" src="https:\/\/streak-stats.demolab.com?user=Sankalpa0011&theme=dark&cache=force" alt="Sankalpa0011" \/>/d' README.md
          echo '<p><img align="center" src="https://streak-stats.demolab.com?user=Sankalpa0011&theme=dark&cache=force" alt="Sankalpa0011" /></p>' >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest GitHub streak stats'
          git push
